# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  
  config.vm.define "web" do |web_config|
    web_config.vm.network :private_network, ip: "192.168.56.101"
    web_config.vm.hostname = "admin"
    web_config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = true
    end
    web_config.vm.provision :shell, path: "bootstrap.sh"
  end


end



