# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  
  config.vm.define "admin" do |admin_config|
    admin_config.vm.network :private_network, ip: "192.168.56.101"
    admin_config.vm.hostname = "admin"
    admin_config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    admin_config.vm.provision :shell, path: "bootstrap_admin.sh"
  end

end



