---
  - debug:
      msg: "Adding hosts in group web: {{groups['web']}}"

  - name: Make sure the known hosts file exists
    file:
      path: /home/vagrant/.ssh/id_rsa.pub
      state: touch

  - name: Check host name availability
    shell: "ssh-keygen -f /home/vagrant/.ssh/known_hosts -F {{ item }}"
    with_items: "{{groups['web']}}"
    register: all_ssh_hosts_check
    ignore_errors: yes

  - name: Scan the public key
    shell: "/usr/bin/ssh-keyscan {{ item.item }} >> /home/vagrant/.ssh/known_hosts"
    with_items: "{{all_ssh_hosts_check.results}}"
    when: item.stdout == ""

  - name: Generate ssh key for user vagrant
    user:
     name: vagrant
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa
